# GitHub CLI hosts configuration
# Get this file after running: gh auth login
#
# Example format:
# github.com:
#     oauth_token: gho_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#     user: your-username
#     git_protocol: ssh
